import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const actions = [
  ['✎', 'File an RTI Request', 'Ask a public authority for information', 'file'],
  ['↗', 'File First Appeal', 'Appeal if you are not satisfied with the response', 'appeal'],
  ['⌕', 'Track Application', 'Check the status of your RTI request or appeal', 'track'],
  ['▣', 'My Applications', 'View your past applications and responses', 'apps'],
];
const authorities = ['Ministry of Railways', 'Ministry of Education', 'Ministry of External Affairs', 'Department of Pension & Pensioners’ Welfare'];

function Header({ hindi, setHindi, onStart, activeRoute = window.location.hash }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const nav = hindi ? ['होम', 'आरटीआई दाखिल करें', 'प्रथम अपील', 'आवेदन ट्रैक करें', 'लोक प्राधिकरण', 'आरटीआई कैसे काम करता है', 'संसाधन'] : ['Home', 'File RTI', 'First Appeal', 'Track Request', 'Public Authorities', 'How RTI Works', 'Resources'];
  return <>
    <a className="skip" href="#main">Skip to main content</a>
    <div className="topbar"><div className="wrap topin"><span>भारत सरकार &nbsp;|&nbsp; Government of India</span><span>Department of Personnel &amp; Training</span></div></div>
    <header><div className="wrap headerin">
      <a className="brand" href="#home"><span className="emblem">✺</span><span><b>RTI Online</b><small>An initiative of DoPT, Government of India</small></span></a>
      <button className="menubtn" aria-label="Open menu" onClick={() => setMenuOpen(!menuOpen)}>☰</button>
      <nav className={menuOpen ? 'open' : ''}>{nav.map((n, i) => { const hrefs = ['home', 'file', 'first-appeal', 'track', 'authority', 'works', 'resources']; const href = `#${hrefs[i]}`; return <a key={n} className={activeRoute === href ? 'active' : ''} href={href} onClick={() => setMenuOpen(false)}>{n}</a>; })}</nav>
      <div className="tools"><button className="icon" aria-label="Focus search" onClick={() => document.querySelector('#search')?.focus()}>⌕</button><button className="lang" onClick={() => setHindi(!hindi)}>{hindi ? 'EN' : 'हिं'}</button><a className="login" href="#login">Log in</a><a className="register" href="#register">Register</a></div>
    </div></header>
  </>;
}

function Wizard({ open, onClose }) {
  const [step, setStep] = useState(1);
  return open ? <div className="modal" role="dialog" aria-modal="true" aria-labelledby="wiztitle"><div className="modal-card">
    <button className="close" onClick={onClose} aria-label="Close">×</button><div className="eyebrow">NEW APPLICATION</div><h2 id="wiztitle">{step === 1 ? 'Start an RTI request' : 'Choose a public authority'}</h2><p className="muted">We’ll guide you through the application one step at a time.</p>
    <div className="progress">{[1, 2, 3, 4, 5].map((n) => <React.Fragment key={n}><span className={n <= step ? 'current' : ''}>{n}</span>{n < 5 && <i />}</React.Fragment>)}</div>
    {step === 1 ? <><label htmlFor="request">What information do you need?</label><textarea id="request" placeholder="For example: I want to know the status of road work in my area." /></> : <><label htmlFor="authority-input">Search by ministry, department or authority</label><input id="authority-input" className="wizard-input" placeholder="Start typing an authority name..." /></>}
    <div className="modal-foot"><span>Step {step} of 5</span><button className="primary" onClick={() => setStep(Math.min(5, step + 1))}>{step === 5 ? 'Review application →' : 'Continue →'}</button></div>
  </div></div> : null;
}

function Search() { const [query, setQuery] = useState(''); const hits = query ? authorities.filter(a => a.toLowerCase().includes(query.toLowerCase()) || query.toLowerCase().includes(a.split(' ')[2]?.toLowerCase() || '___')) : []; return <section className="search-section"><div className="wrap"><label htmlFor="search">Find what you need</label><div className="global-search"><span>⌕</span><input id="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search public authority, department, or type your query..." /><kbd>⌘ K</kbd></div><div className="popular"><span>Popular:</span>{['Railway recruitment', 'Passport application', 'Pension'].map(x => <button key={x} onClick={() => setQuery(x)}>{x}</button>)}</div>{query && <div className="results">{(hits.length ? hits : ['No exact match — try a ministry or department name']).map(a => <button key={a}>{a}<span>→</span></button>)}</div>}</div></section>; }

function ChatBot() { const [open, setOpen] = useState(false); const [messages, setMessages] = useState([{ role: 'bot', text: 'Hello! I can help you find your way around RTI Online. Try “I want to file an RTI” or “track my application”.' }]); const [text, setText] = useState(''); const send = async (value = text) => { if (!value.trim()) return; const question = value.trim(); setText(''); setMessages(m => [...m, { role: 'user', text: question }]); try { const res = await fetch('http://localhost:8000/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: question }) }); const data = await res.json(); setMessages(m => [...m, { role: 'bot', text: data.reply, action: data.action }]); } catch { setMessages(m => [...m, { role: 'bot', text: 'The help assistant is temporarily unavailable. You can use the main navigation above to continue.' }]); } }; return <div className="chatbot"><button className="chat-launcher" onClick={() => setOpen(!open)} aria-label="Open navigation assistant">{open ? '×' : '✦'}<span>{!open && 'Help'}</span></button>{open && <section className="chat-panel" role="dialog" aria-label="RTI navigation assistant"><div className="chat-head"><div><b>RTI Help Assistant</b><small>Navigation support · Not legal advice</small></div><button onClick={() => setOpen(false)}>×</button></div><div className="chat-messages">{messages.map((m, i) => <div className={`chat-message ${m.role}`} key={i}><p>{m.text}</p>{m.action && <a href={m.action} onClick={() => setOpen(false)}>Go there →</a>}</div>)}</div><div className="chat-suggestions">{['File an RTI', 'Track application', 'Find authority'].map(x => <button key={x} onClick={() => send(x)}>{x}</button>)}</div><form className="chat-input" onSubmit={e => { e.preventDefault(); send(); }}><input value={text} onChange={e => setText(e.target.value)} placeholder="Ask how to navigate..." aria-label="Chat message" /><button aria-label="Send message">↑</button></form></section>}</div>; }

function App() {
  const [hindi, setHindi] = useState(false); const [wizard, setWizard] = useState(false); const [route, setRoute] = useState(window.location.hash || '#home');
  useEffect(() => { const onHash = () => setRoute(window.location.hash || '#home'); window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []);
  const c = hindi ? { hero: 'सूचना का आपका अधिकार', sub: 'एक अधिक पारदर्शी भारत', desc: 'आरटीआई आवेदन दाखिल करें, स्थिति ट्रैक करें और सार्वजनिक प्राधिकरणों से जानकारी आसानी से, सुरक्षित रूप से और ऑनलाइन प्राप्त करें।' } : { hero: 'Your Right to Information', sub: 'A more transparent India', desc: 'File RTI applications, track status, and seek information from public authorities — easily, securely, and online.' };
  const go = (hash) => { window.location.hash = hash; };
  const page = route.replace('#', '').split('/')[0];
  if (page !== 'home' && page !== 'works' && page !== 'help') return <><Header hindi={hindi} setHindi={setHindi} activeRoute={route} /><RoutePage page={page} hindi={hindi} go={go} onStart={() => setWizard(true)} /><Footer /><Wizard open={wizard} onClose={() => setWizard(false)} /></>;
  return <><Header hindi={hindi} setHindi={setHindi} /><main id="main"><section className="hero" id="home"><div className="wrap hero-grid"><div><div className="eyebrow"><i /> DIGITAL INDIA · CITIZEN SERVICES</div><h1>{c.hero}<br /><em>{c.sub}</em></h1><p>{c.desc}</p><div className="hero-actions"><button className="primary" onClick={() => setWizard(true)}>Start an RTI request <span>→</span></button><a className="textlink" href="#works">See how it works <span>→</span></a></div></div><div className="hero-art"><div className="seal">✺<span>सत्यमेव जयते<br /><small>TRUTH ALONE TRIUMPHS</small></span></div><div className="art-line" /><b>Information is<br />a citizen’s right.</b></div></div></section><Search /><section className="wrap actions"><div className="section-head"><div><div className="eyebrow">GET STARTED</div><h2>What would you like to do?</h2></div><a href="#help">Explore all services →</a></div><div className="action-grid">{actions.map(([icon, title, desc, type], i) => <button className={`action-card ${i === 0 ? 'featured' : ''}`} key={type} onClick={() => type === 'file' ? setWizard(true) : go(`#${type === 'appeal' ? 'first-appeal' : type}`)}><span className="action-icon">{icon}</span><span><b>{title}</b><small>{desc}</small></span><strong>→</strong></button>)}</div></section><Notice /><HowItWorks onStart={() => setWizard(true)} /><Help /></main><Footer /><Wizard open={wizard} onClose={() => setWizard(false)} /><ChatBot /></>;
}

function RoutePage({ page, hindi, go, onStart }) {
  const hi = hindi; const title = { file: hi ? 'ऑनलाइन आरटीआई आवेदन' : 'Online RTI Request', 'first-appeal': hi ? 'प्रथम अपील दाखिल करें' : 'File First Appeal', track: hi ? 'आवेदन की स्थिति देखें' : 'Track Application', apps: hi ? 'मेरे आवेदन' : 'My Applications', authority: hi ? 'लोक प्राधिकरण खोजें' : 'Find a Public Authority', manual: hi ? 'आरटीआई उपयोगकर्ता मार्गदर्शिका' : 'RTI User Manual', contact: hi ? 'संपर्क करें' : 'Contact Us', faq: 'Frequently Asked Questions', payment: hi ? 'भुगतान मिलान' : 'Payment Reconciliation' }[page] || 'RTI Online';
  if (page === 'file') return <main className="route-page wrap"><div className="eyebrow">RTI ONLINE · STEP 1 OF 6</div><h1>{title}</h1><p className="route-intro">{hi ? 'आवेदन शुरू करने के लिए अपना ईमेल और मोबाइल नंबर दर्ज करें।' : 'Enter your email and mobile number to begin your application.'}</p><div className="legacy-form"><label>Email ID <b>*</b><input type="email" placeholder="e.g. user@domain.com" /></label><label>Mobile Number<input placeholder="Enter Mobile Number" /></label><label>Security code <b>*</b><input placeholder="Enter the code shown" /></label><div className="form-actions"><button className="primary" onClick={onStart}>Continue →</button><button className="secondary">Reset</button></div></div><Guidelines hindi={hi} /></main>;
  if (page === 'track') return <main className="route-page wrap"><div className="eyebrow">APPLICATION STATUS</div><h1>{title}</h1><div className="legacy-form"><label>Registration number<input placeholder="RTI/2026/001234" /></label><label>Email or mobile number<input placeholder="Enter your registered contact" /></label><button className="primary">View status →</button></div><div className="timeline"><b>RTI/2026/001234</b><p>✓ Application submitted <small>12 Aug 2026</small></p><p>✓ Payment confirmed <small>12 Aug 2026</small></p><p>✓ Sent to public authority <small>13 Aug 2026</small></p><p className="pending">● Response pending <small>Expected by 11 Sep 2026</small></p></div></main>;
  if (page === 'apps') return <main className="route-page wrap"><div className="eyebrow">CITIZEN DASHBOARD</div><h1>{title}</h1><div className="dashboard-cards"><div><b>3</b><span>Active Requests</span></div><div><b>5</b><span>Responses Received</span></div><div><b>1</b><span>First Appeals</span></div><div><b>2</b><span>Drafts</span></div></div><div className="table-card"><h2>Recent applications</h2><p>RTI/2026/001234 · Ministry of Railways · Response pending</p><p>RTI/2026/000981 · Ministry of Education · Response received</p><button className="primary" onClick={onStart}>+ New RTI Request</button></div></main>;
  return <main className="route-page wrap"><div className="eyebrow">CITIZEN SERVICES</div><h1>{title}</h1><p className="route-intro">{page === 'authority' ? 'Search ministries, departments and Central Government organisations.' : 'This section is ready for your RTI Online workflow.'}</p><div className="legacy-form"><input placeholder={page === 'authority' ? 'Search public authority or department...' : 'Search this section'} /><button className="primary">Search →</button></div>{page === 'authority' && <div className="authority-list">{authorities.map(a => <article key={a}><b>{a}</b><span>Central Government · View details →</span></article>)}</div>}{page === 'first-appeal' && <div className="callout"><b>Are you satisfied with the response?</b><p>Choose an option to continue with your application.</p><button className="secondary">Yes, I’m satisfied</button> <button className="primary">No, file First Appeal</button></div>}{['manual','faq','contact','payment'].includes(page) && <Guidelines hindi={hi} />}</main>;
}

function Guidelines({ hindi }) { return <section className="guidelines"><h2>{hindi ? 'पोर्टल के उपयोग के दिशानिर्देश' : 'Guidelines for use of RTI Online portal'}</h2><ol><li>This portal can be used by Indian citizens to file RTI applications and make online payment.</li><li>Applications may be filed with Ministries, Departments and other Public Authorities of the Central Government.</li><li>Fields marked with <b>*</b> are mandatory. Please review your application before payment.</li><li>The text of an application should be concise and within the displayed character limit.</li><li>Payment may be made through internet banking, cards, RuPay or UPI.</li><li>For State Government authorities, including Government of NCT Delhi, use the relevant State portal.</li></ol><label><input type="checkbox" /> I have read and understood the above guidelines.</label></section>; }
function Notice() { const [visible, setVisible] = useState(true); return visible && <section className="wrap notice"><span className="notice-icon">!</span><div><b>Important notice</b><p>RTI applications for State Government public authorities, including Government of NCT Delhi, should not be filed through this portal. If filed, the application may be returned without refund.</p></div><button onClick={() => setVisible(false)} aria-label="Dismiss notice">×</button></section>; }
function HowItWorks({ onStart }) { return <section className="feature" id="works"><div className="wrap feature-grid"><div><div className="eyebrow">A SIMPLE PROCESS</div><h2>How to file an RTI</h2><p>Ask for information from a Central Government public authority in a few clear steps.</p><button className="secondary" onClick={onStart}>Start your application →</button></div><div className="steps">{[['01', 'Choose a service', 'Select the request type that fits your need.'], ['02', 'Write your question', 'Tell us what information you need, in your own words.'], ['03', 'Review & submit', 'Check your details, pay the application fee, and submit.']].map(x => <div className="step" key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><p>{x[2]}</p></div></div>)}</div></div></section>; }
function Help() { return <section className="wrap help" id="help"><div className="section-head"><div><div className="eyebrow">NEED A HAND?</div><h2>We’re here to help</h2></div><a href="#help">Visit Help Center →</a></div><div className="help-grid">{[['?', 'First time filing an RTI?', 'Understand the process in plain language.', 'Read the guide →'], ['⌕', 'Looking for a public authority?', 'Search our directory of Central Government authorities.', 'Find an authority →'], ['▤', 'Frequently asked questions', 'Quick answers to common questions about RTI.', 'Browse FAQs →']].map(x => <article key={x[1]}><span>{x[0]}</span><b>{x[1]}</b><p>{x[2]}</p><a href="#works">{x[3]}</a></article>)}</div></section>; }
function Footer() { return <footer><div className="wrap footer-grid"><div className="brand"><span className="emblem">✺</span><span><b>RTI Online</b><small>Government of India</small></span></div><div><b>Quick links</b><a href="#file">File RTI</a><a href="#track">Track request</a><a href="#authority">Public authorities</a></div><div><b>Resources</b><a href="#works">How RTI works</a><a href="#resources">FAQ &amp; user manual</a><a href="#help">Help center</a></div><div><b>Accessibility</b><p>Built for every citizen.<br />Screen-reader friendly · Keyboard accessible</p></div></div><div className="wrap copyright">© Government of India &nbsp;·&nbsp; Privacy &nbsp;·&nbsp; Terms of use</div></footer>; }

createRoot(document.getElementById('app')).render(<App />);
